### Admin Login
POST http://localhost:5000/api/admin/login
Content-Type: application/json

{
  "email": "saleh@gmail.com",
  "password": "saleh12"  
}
### Temporary Login
POST http://localhost:5000/api/admin/temp-login
Content-Type: application/json

{
  "email": "admin1@example.com"
}


### Add New Admin
POST http://localhost:5000/api/admin/add-admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTQ0NWQ4ZjIzYjI3Mjg3YTM5MTg5OCIsInJvbGUiOiJzdXBlcmFkbWluIiwiaWF0IjoxNzMzNTg0OTAyLCJleHAiOjE3MzM2NzEzMDJ9.nZ3VFFZ2EMTkNH6o2t6_3czlY9cVC6fbeN6Ir5Y72f8

{
  "name": "saleh",
  "email": "saleh@gmail.com",
  "password": "saleh12",
  "role": "admin"
}



### Fetch All Users
GET http://localhost:5000/api/admin/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTQ0NWQ4ZjIzYjI3Mjg3YTM5MTg5OCIsInJvbGUiOiJzdXBlcmFkbWluIiwiaWF0IjoxNzMzNTg0OTAyLCJleHAiOjE3MzM2NzEzMDJ9.nZ3VFFZ2EMTkNH6o2t6_3czlY9cVC6fbeN6Ir5Y72f8


### Update User
PUT http://localhost:5000/api/admin/update-user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTQ0NWQ4ZjIzYjI3Mjg3YTM5MTg5OCIsInJvbGUiOiJzdXBlcmFkbWluIiwiaWF0IjoxNzMzNTc2NzIwLCJleHAiOjE3MzM2NjMxMjB9.Yl4VkykJTOECFxy-GOTIaSChJPFGhbN3fM3fE3bcf5E


{
  "userId": "675434ba24455f6b6d0bb1c7",
  "updates": {
    "name": "Muhammad Saleh",
    "email": "salehuser@gmail.com"
  }
}


### Delete User
DELETE http://localhost:5000/api/admin/delete-user/675434ba24455f6b6d0bb1c7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTQ0NWQ4ZjIzYjI3Mjg3YTM5MTg5OCIsInJvbGUiOiJzdXBlcmFkbWluIiwiaWF0IjoxNzMzNTg0OTAyLCJleHAiOjE3MzM2NzEzMDJ9.nZ3VFFZ2EMTkNH6o2t6_3czlY9cVC6fbeN6Ir5Y72f8


### Update Bot Status
PATCH http://localhost:5000/api/admin/bots
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTQ0NWQ4ZjIzYjI3Mjg3YTM5MTg5OCIsInJvbGUiOiJzdXBlcmFkbWluIiwiaWF0IjoxNzMzNTg0OTAyLCJleHAiOjE3MzM2NzEzMDJ9.nZ3VFFZ2EMTkNH6o2t6_3czlY9cVC6fbeN6Ir5Y72f8

{
  "botId": "6754349a24455f6b6d0bb1b7",
  "status": "approved"  
}


### Fetch Analytics (Bot and User Data)
GET http://localhost:5000/api/admin/analytics
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTQ0NWQ4ZjIzYjI3Mjg3YTM5MTg5OCIsInJvbGUiOiJzdXBlcmFkbWluIiwiaWF0IjoxNzMzNTg0OTAyLCJleHAiOjE3MzM2NzEzMDJ9.nZ3VFFZ2EMTkNH6o2t6_3czlY9cVC6fbeN6Ir5Y72f8


### Fetch Chat Rooms
GET http://localhost:5000/api/admin/chat-rooms
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTQ0NWQ4ZjIzYjI3Mjg3YTM5MTg5OCIsInJvbGUiOiJzdXBlcmFkbWluIiwiaWF0IjoxNzMzNTg0OTAyLCJleHAiOjE3MzM2NzEzMDJ9.nZ3VFFZ2EMTkNH6o2t6_3czlY9cVC6fbeN6Ir5Y72f8


### Delete Chat Room
DELETE http://localhost:5000/api/admin/delete-chat-room/CHAT_ROOM_ID_HERE
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTQ0NWQ4ZjIzYjI3Mjg3YTM5MTg5OCIsInJvbGUiOiJzdXBlcmFkbWluIiwiaWF0IjoxNzMzNTg0OTAyLCJleHAiOjE3MzM2NzEzMDJ9.nZ3VFFZ2EMTkNH6o2t6_3czlY9cVC6fbeN6Ir5Y72f8
